-- Provider/model reference data is seeded idempotently inside
-- supabase/migrations/20260825090000_core_schema.sql so that `db push`
-- seeds the hosted project too (seed.sql only runs on local resets).
-- Nothing further to seed here.
